repo:  https://github.com/openwrt/openwrt.git
branch: openwrt-22.03
revision: ea845f76ea2406a4c70d96141d6386b81bba5431
output_dir: ./output

patch_folders:
  - patches_new/base/
  - patches_new/ath79/
  - patches_new/ipq40xx/
  - patches_new/ipq806x/
  - patches_new/ipq807x/
  - patches_new/ramips/
  - patches_new/rest/
  - patches_new/wifi/
  - patches_new/x86/
